name: Unpublish Netlify Site

on:
  workflow_dispatch:  # Manually trigger the action

jobs:
  unpublish-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Unpublish latest deploy
        run: |
          # Fetch the latest deploy ID
          deploy_id=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            "https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys?per_page=1" \
            | jq -r '.[0].id')

          echo "Unpublishing deploy: $deploy_id"

          # Delete the latest deploy to unpublish the site
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            "https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys/$deploy_id"
